n=input("enter the value:")
n1=input("enter the value:")
n2=input("enter the value:")
n3=input("enter the value:")
a=input("enter the age:")
a1=input("enter the age:")
a2=input("enter the age:")
a3=input("enter the age:")
e=input("enter the email:")
e1=input("enter the email:")
e2=input("enter the email:")
e3=input("enter the email:")
p=input("enter the ph:")
p1=input("enter the ph:")
p2=input("enter the ph:")
p3=input("enter the ph:")
ad=input("enter the ad:")
ad1=input("enter the ad:")
ad2=input("enter the ad:")
ad3=input("enter the ad:")


print("|-------------------------------------------------------------------------|")
print("|    name  |  age|         email     |    phone  |     address     | ")
print("|-------------------------------------------------------------------------|")
print("|" ,  n,    "  |",  a, " |        ",e,       " |",     p,    "|",     ad ,     "|")
print("|-------------------------------------------------------------------------|")
print("|" , n1,    "  |", a1, " |",       e1,  "|",    p1,    "|",       ad1 ,     "|")
print("|--------------------------------------------------------------------------|")
print("|" ,  n2,    "  |",  a2, " |",          e2,       " |",     p2,    "|",    ad2 ,     "|")
print("|-------------------------------------------------------------------------|")
print("|" ,  n3,    "  |",  a3, " |",          e3,       " |",     p3,    "|",    ad3 ,     "|")
print("|-------------------------------------------------------------------------|")